services:
  - type: web
    name: omni-route-render-backend
    env: docker
    plan: free
    region: virginia
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "20128"
      - key: HOSTNAME
        value: 0.0.0.0
      - key: NODE_ENV
        value: production
      - key: DATA_DIR
        value: /app/data
      - key: NEXT_PUBLIC_BASE_URL
        value: https://omni-route-render-backend.onrender.com
      - key: BASE_URL
        value: https://omni-route-render-backend.onrender.com
      - key: AUTH_COOKIE_SECURE
        value: "true"
